# Generated by Django 5.1.5 on 2025-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountManager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteraccount",
            name="account_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
