# Generated by Django 5.1.5 on 2025-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountManager", "0003_remove_twitteraccount_access_token_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteraccount",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="twitteraccount",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="twitteraccount",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
