# Generated by Django 5.1.5 on 2025-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountManager", "0004_twitteraccount_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteraccount",
            name="twitter_user_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
